include $(ROOT)/build/common.mk

NAME      := nested-svm-vmrun
CATEGORY  := in-development
TEST-ENVS := hvm64

TEST-EXTRA-CFG := extra.cfg.in

obj-perenv += main.o entry.o

include $(ROOT)/build/gen.mk
