include $(ROOT)/build/common.mk

NAME      := nested-svm-vmload-negative
CATEGORY  := in-development
TEST-ENVS := hvm64

TEST-EXTRA-CFG := extra.cfg.in

obj-perenv += main.o ../nested-svm/svm-negative.o

include $(ROOT)/build/gen.mk