include $(ROOT)/build/common.mk

NAME      := nested-svm-vmsave-negative
CATEGORY  := in-development
TEST-ENVS := hvm64

TEST-EXTRA-CFG := extra.cfg.in

obj-perenv += ../nested-svm/svm-negative.o main.o

include $(ROOT)/build/gen.mk